DEBUG = True

DIALECT = 'mysql'
DRIVE = 'pymysql'
USERNAME = 'root'
PASSWORD = 'Name@4321'
HOST = '127.0.0.1'
PORT = '3306'
DATABASE = 'crypto'
SECRET_KEY = 'TEST-KEY'

SQLALCHEMY_DATABASE_URI = "{}+{}://{}:{}@{}:{}/{}".format(DIALECT, DRIVE, USERNAME, PASSWORD, HOST, PORT, DATABASE)
SQLALCHEMY_TRACK_MODIFICATIONS = False
